name = "trtc-usersig-workers"
compatibility_date = "2023-01-01"

compatibility_flags = [ "nodejs_compat" ]

main = "src/index.ts"

[vars]
SDKAPPID = 140011234444
SECRET = "xxxxxxxxxx"


[site]
bucket = "./assets"


